version: '3.8'
services:
  pg:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=assignment
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - pg
